Cluster Protocol
================

## Setup 

```{r Setup, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
library(tidyverse)
```

### Import Data

```{r}
load('cleaned/ps_samfilt.Rdata')
load('intermed/clst_samfilt.Rdata')
ls()
```

### Look at the clusters

```{r}
head(clsts)
	# Each sequence has its own row, in the order they were originally listed in
	# The cluster number that each sequence belongs to is listed in its row in
	# the "cluster" column

# Count the clusters
n_distinct(clsts$cluster)

# Count the number of clusters of each size
clsts %>% count(cluster, name = 'size') %>% count(size, name = 'count') %>%
    arrange(desc(size))
```

### Get a consensus sequence for each cluster, using ambiguity codes

```{r}
# A function to convert a set of sequences into a consensus sequence
get_conseq = function(x){
	if (length(x) > 1){
		aln = AlignSeqs(DNAStringSet(x))
	} else {
		aln = DNAStringSet(x)
	}
	con = ConsensusSequence(aln)
	return(as.character(con))
}

conseq = (clsts
		  %>% group_by(cluster)
		  %>% summarize(consensus = get_conseq(seqs)))

head(conseq)
```

### Assign taxonomy to the consensus sequence

```{r}
clstax = assignTaxonomy(conseq$consensus, 
			refFasta = '~/Disk2/CommonData/SILVA/silva_nr_v132_train_set.fa',
			tryRC = TRUE, multithread = 8)

head(clstax)
```

### Group up the ASV table into a cluster table

```{r}
head(clsts)

# Turn the ASV table into a data frame and add the sequences as a column
asvdf = (asvtab
		  %>% data.frame()
		  %>% mutate(seqs = rownames(.))
		  %>% select(seqs, everything()))
head(asvdf)

# Join with the cluster table
asvdf = (asvdf
		  %>% left_join(clsts, by = 'seqs')
		  %>% select(cluster, everything(), -seqs))
head(asvdf)

# Sum the counts at each sample within each cluster. This groups all the 'host'
# sequences into an NA cluster, which I then filter out
clstdf = (asvdf
		%>% group_by(cluster)
		%>% summarise_all(sum)
		%>% ungroup()
		%>% filter(!is.na(cluster))
		%>% data.frame())
dim(clstdf)

# Add the cluster consensus sequences as the rownames of the new table 
all(conseq$cluster == clstdf$cluster)
rownames(clstdf) = conseq$consensus
head(clstdf)

# Make it a matrix just like dada2 produces
clstab = as.matrix(select(clstdf, -cluster))
clstab[1:10,1:10]
```

### Done

Now we have a cluster count table `clstab`, and an associated taxonomy table
`clstax` and should be able to put them in phyloseq and do stuff.

```{r}

```
