# Identify and deal with any problems with sequenced samples.

## Setup
```{r}
library(phyloseq)
library(tidyverse)
library(AfterSl1p)
```

## Import

```{r}
load('cleaned/ps_full.Rdata')
```

## Investigate samples

```{r, cache=TRUE, cache.extra=tools::md5sum('cleaned/ps_full.Rdata')}
samdat = data.frame(sample_data(ps))
samdat = (samdat
          %>% mutate(Depth = sample_sums(ps)))
head(samdat)

ggplot(samdat, aes(x = DiseaseType, y = Depth)) +
    geom_jitter(alpha = 0.3) +
    scale_y_log10() +
    facet_wrap(~Timepoint)

summary(sample_sums(ps))
filter(samdat, Depth < 100)
filter(samdat, Depth < 1000)
filter(samdat, Depth < 5000) %>% nrow()
filter(samdat, Depth < 10000) %>% nrow()
```

There are 6 samples with fewer than 100 sequences, an additional 2 with fewer
than 1000, 34 total with fewer than 5000, and 162 with fewer than 10,000.

From the plot, it doesn't look like there is bias according to condition or
timepoint. 162 out for 4,000 is not a bad ratio. I'll just remove them.


```{r, cache=TRUE, cache.extra=tools::md5sum('cleaned/ps_full.Rdata')}
load('cleaned/ps_samfilt.Rdata')
```
